### ISSUE TITLE
make already saved localities refresh their data

### ISSUE THREAD

**Issue by alexandra-prasolova** [alexandra-prasolova/Raccons-Weather#8]
*actual* 
When locality is added its data is saved once and never changes, but weather around the world changes all the time (what a surprise) 
*expected*
Saved localities should get new data about weather when the app is opened

**Comment by DmytroLisitsyn** [comment]
Also add data updating on "pull to refresh" action in location list and location details screen. 😉

**Comment by DmytroLisitsyn** [comment]
https://github.com/alexandra-prasolova/Raccons-Weather/pull/12
